apiVersion: v1
kind: ConfigMap
metadata:
  name: printnet-config
  namespace: printnet
data:
  NODE_ENV: "production"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "printnet_db"
  MQTT_URL: "mqtt://mosquitto-service:1883"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  ELASTICSEARCH_URL: "http://elasticsearch-service:9200"
  PROMETHEUS_URL: "http://prometheus-service:9090"
