apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: printnet
data:
  nginx.conf: |
    upstream api_backend {
        least_conn;
        server printnet-api-service:3000 max_fails=3 fail_timeout=30s;
    }

    upstream auth_backend {
        least_conn;
        server printnet-auth-service:3001 max_fails=3 fail_timeout=30s;
    }

    upstream orders_backend {
        least_conn;
        server printnet-orders-service:3002 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 80;
        server_name _;

        # Enable compression
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
        limit_req_zone $binary_remote_addr zone=auth:10m rate=5r/s;

        # Health check endpoint
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }

        # Authentication endpoints
        location /api/auth/ {
            limit_req zone=auth burst=20 nodelay;
            proxy_pass http://auth_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 5s;
            proxy_read_timeout 30s;
        }

        # Orders endpoints
        location /api/orders/ {
            limit_req zone=api burst=50 nodelay;
            proxy_pass http://orders_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 5s;
            proxy_read_timeout 60s;
        }

        # Main API endpoints
        location /api/ {
            limit_req zone=api burst=50 nodelay;
            proxy_pass http://api_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 5s;
            proxy_read_timeout 30s;
        }

        # Frontend static files (if needed)
        location / {
            proxy_pass http://api_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
