apiVersion: apps/v1
kind: Deployment
metadata:
  name: printnet-orders
  namespace: printnet
  labels:
    app: printnet-orders
spec:
  replicas: 3
  selector:
    matchLabels:
      app: printnet-orders
  template:
    metadata:
      labels:
        app: printnet-orders
    spec:
      containers:
        - name: printnet-orders
          image: printnet-orders:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: printnet-config
                  key: NODE_ENV
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: printnet-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: printnet-config
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: printnet-config
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: printnet-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: printnet-secret
                  key: DB_PASSWORD
            - name: MQTT_URL
              valueFrom:
                configMapKeyRef:
                  name: printnet-config
                  key: MQTT_URL
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: printnet-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: printnet-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: printnet-secret
                  key: REDIS_PASSWORD
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
  name: printnet-orders-service
  namespace: printnet
spec:
  selector:
    app: printnet-orders
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: printnet-orders-hpa
  namespace: printnet
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: printnet-orders
  minReplicas: 3
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
